apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-b-resource-quota
  namespace: team-b
spec:
  hard:
    requests.cpu: "0.5"
    requests.memory: "500Mi"
    limits.cpu: "2"
    limits.memory: "2Gi"
    pods: "3"
