apiVersion: v1
kind: Pod
metadata:
  name: team-c-pod
  namespace: team-c
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
  tolerations:
    - key: "team"
      operator: "Equal"
      value: team-c
      effect: "NoSchedule"
